### ISSUE TITLE
RTD build is failing

### ISSUE THREAD

**Issue by eslavich** [asdf-format/asdf-standard#297]
See https://readthedocs.org/projects/asdf-standard/builds/16085697/ for example.  We need to update the install script that RTD uses to account for the new package setup.

Also we could use a CI check that runs the build on readthedocs.org so that we can catch this kind of issue in the future.

Thanks @pllim for the report :)

**Comment by pllim** [comment]
For now, you can fix URLs by setting `Advanced Settings -> Default version* -> latest`. It has a last successful build that RTD can fallback on until you fix `en/v1.0.0`.
