### ISSUE TITLE
conda-forge release of `asdf-standard`

### ISSUE THREAD

**Issue by CagtayFabry** [asdf-format/asdf-standard#301]
As mentioned in https://github.com/asdf-format/asdf/issues/1093 with the restructuring and updated dependencies a 'full' asdf install from conda currently is not possible because the `asdf-standard` package is not yet available on conda-forge

```bash
conda create -n asdf_conda python=3.9 asdf pip
conda activate asdf_conda

pip check
>>> asdf 2.10.0 requires asdf-standard, which is not installed.
>>> asdf 2.10.0 requires asdf-transform-schemas, which is not installed.
```

To fix the conda setup a release of `asdf-standard` (and probably `asdf-transform-schemas`) on conda-forge by setting up new feedstocks would be necessary

**Comment by WilliamJamieson** [comment]
@CagtayFabry has this been resolved?

**Comment by CagtayFabry** [comment]
I ran a quick check again and our conda pipelines also seem to work so I think this is now resolved with the updated asdf conda releases 👍
