### ISSUE TITLE
Remove `tag` entry from all asdf-standard schemas

### ISSUE THREAD

**Issue by WilliamJamieson** [asdf-format/asdf-standard#324]
PR #323 removes the `tag` entry from the `time-1.1.0` schema (the tag now only exists within the manifest). This is because the `tag` reference made it impossible to directly extend the `time-1.1.0` schema and then tag it with a new tag in another package.

It is generally, bad practice to include the `tag` within the schema defining the `tag` unless one directly wants to prevent others from extending/re-tagging existing schemas, due to the above issue. Thus `asdf-standard` should remove all these tags to prevent these types of issues in the future.

**Comment by nden** [comment]
Resolved in #326
